# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yoofJ9AJUfGSp8FrDbkVijOPGoWp6HCo
"""

import pickle
import streamlit as st 


pickle_in = open("classifier.pkl","rb")
classifier=pickle.load(pickle_in)


def predict Bank_Note_Authentication(variance,skewness,curtosis,entropy):
    prediction=classifier.predict([[variance,skewness,curtosis,entropy]])
    print(prediction)
    return prediction

def main():
    st.title("Bank_Note_Authentication Prediction")
    variance = st.text_input("variance")
    skewness = st.text_input("skewness")
    curtosisi = st.text_input("curtosis")
    entropy = st.text_input("entropy")
    result=""
    if st.button("Predict"):
        result=predict Bank_Note_Authentication(variance,skewness,curtosis,entropy)
    st.success('The output is {}'.format(result))
    

if __name__=='__main__':
    main()